import { App, shallowReactive } from 'vue'
import { setStoredAppContext } from './storedAppContext'
import type { IDSOptions } from '@/types/IDSOptions'
import { Themes } from '@/enums/Themes'
import { ThemesColors, UiThemes } from '@/types/styles/ColorTheme'
import defaultAvatar from './assets/img/no_user.png'
import { createProxy } from '@/utils/proxy'
import { SPRITE_IDS, SPRITE_FILES } from '@/consts/'
export { SPRITE_IDS, SPRITE_FILES }
export {
  ThemesColors,
  UiThemes,
  Colors,
  Sizes,
  FontSizes,
  FontWeights,
  Radiuses,
  Spaces,
  AvatarSizes,
  LineHeights,
  Durations,
  MediaQueries
} from '@/types'

export type {
  IDSOptions,
  IModalState,
  IDrawerState,
  ISideBarLink,
  ISideBarMenuItemEnrichment,
  ITableData,
  ISideBarApp,
  ISideBarMenuItem,
  ISideBar,
  ChipSizeUnion,
  ColorsUnion,
  ICheckboxMainCheckbox,
  IComment,
  IToast,
  ICommentTitle,
  IToastAction,
  IFilterPreset,
  ITooltip,
  ToastPositionsUnion,
  TableCardState,
  ITableCardCloseState,
  ITableCardOpenState,
  ITableSortState,
  ColorTypes,
  SpaceTypes,
  ITableSort,
  IconsListUnion,
  TooltipPositionsUnion,
  FilterRelationValue,
  FilterTextValue,
  FilterConditionValue,
  ITablePlaceholders,
  IFilterPlaceholders,
  IRoute,
  ITableTotals,
  ITableColumn,
  ButtonSizeUnion,
  ButtonTypeUnion,
  ButtonVariationUnion,
  TitleVariationsUnion,
  ITooltipInstance,
  WeightsUnion,
  IFilter,
  IFilterValue,
  HorizontalAlignmentUnion,
  SizeTypes,
  FilterConditionName,
  IFilterRangeValue,
  DropdownListPositionsUnion,
  SpacesUnion,
  CellSizesUnion,
  ISidebarThemeConfig,
  IBaseFilter,
  ISelectOption,
  ISelectOptions,
  ISelectGroupOptions,
  FontWeightTypes,
  ChipSizeModifiersUnion,
  ChipVariationUnion,
  AvatarSizeTypes,
  ColorTheme,
  ColorThemes,
  ColumnAlignmentUnion,
  ColumnJustifyAlignmentUnion,
  ColumnSpanUnion,
  DateFilterValue,
  DatepickerTypesUnion,
  DatepickerFormatUnion,
  DatepickerFormatsObject,
  DayjsFormatUnion,
  DrawerPositionsUnion,
  DurationsTypesUnion,
  DatepickerOutputFormatUnion,
  DropdownPositionsUnion,
  FontWeightsUnion,
  DatepickerFormatsVariationsUnion,
  DatePickerValue,
  LineHeightTypes,
  DirectionsUnion,
  DatepickerFormatsObjectFormat,
  DurationsTypes,
  FontSizeTypes,
  FilterRelationName,
  FilterTextName,
  FilterMoreLessConditionName,
  IButton,
  FilterOption,
  ICell,
  ICheckbox,
  IFilterCondition,
  IFilterDateValue,
  ICollapse,
  IButtonStyleOptions,
  IChipStyleOptions,
  IDrawerServiceState,
  IFilterParsedValue,
  IFilterBaseTag,
  IFilterDateName,
  IFilterDateTag,
  IFilterValueFilter,
  IFilterValueFilterName,
  IFilterParsedValueFilterName,
  IFilterParsedValueFilter,
  IFilterRangeName,
  IFilterRangeTag,
  IFilterRelationTag,
  IFilterTag,
  IFilterTextTag,
  IRangeFilter,
  IRelationFilter,
  IRelationApiFilter,
  IRelationOptionsFilter,
  IDatepickerPlaceholders,
  IDirections,
  IFastFilter,
  InputTypesUnion,
  IDatepickerPreset,
  IDropdown,
  IDrawerProps,
  IInput,
  IModalServiceState,
  IModalProps,
  InputValue,
  IRadioGroupOption,
  IRadio,
  ICollapseEmitPayload,
  IRadioGroupOptions,
  ISideBarChatra,
  ISideBarLang,
  ISidebarThemeConfigProvide,
  ISelectGroupOption,
  ITableCardProps,
  ITableColumnBase,
  ITableColumnEnriched,
  RangeFilterValue,
  SizesUnion,
  PreviewSizesUnion,
  IPreview,
  ITableColumnWidth,
  ITableColumnMinWidth,
  ITitle,
  ITab,
  RadioVariationUnion,
  TitleSizesUnion,
  TooltipSizesUnion,
  TabVariationUnion,
  IGridGutters,
  IRouteWithName,
  IRouteWithPath,
  ITooltipStyles,
  MediaQueryTypes,
  RadioTypes,
  RadioGroupDirectionUnion,
  SelectListDirectionsUnion,
  SortDirection
} from '@/types'
export { TABLE } from '@/consts'
export {
  Themes,
  Weights,
  TitleVariations,
  ChipSize,
  ChipSizeModifiers,
  ChipModifiers,
  CellSizes,
  ButtonSize,
  TooltipSizes,
  Autocomplete,
  ToastPositions,
  DropdownPositions,
  HorizontalAlignment,
  ColumnAlignment,
  DropdownListPositions,
  TooltipPositions,
  ColumnJustifyAlignment,
  ButtonType,
  SidebarTheme,
  ModalVariation,
  FilterTypes,
  InputTypes,
  PreviewSizes,
  FilterRelations,
  Directions,
  DatepickerTypes,
  ColumnSizes,
  RadioVariation,
  RadioGroupDirection,
  DatepickerFormatsVariations,
  DatepickerFormat,
  DatepickerOutputFormat,
  ButtonModifiers,
  DayjsFormat,
  DrawerPositions,
  Media,
  FileContentType,
  TabVariations,
  TitleSizes,
  SelectGroupKeys,
  SelectListDirections
} from '@/enums'
export {
  sanitize,
  createProxy,
  dayjs,
  dayjsLocales,
  iconNameToComponentName,
  mcGridColAdaptiveProps,
  mcTitleAdaptiveProps,
  mcSvgIconAdaptiveProps
} from '@/utils'

export {
  colors,
  durations,
  easings,
  fontFamilies,
  fontSizes,
  fontWeights,
  gradients,
  letterSpacings,
  lineHeights,
  mediaQueries,
  opacities,
  sizes,
  spacings,
  zIndexes,
  borderRadius,
  boxShadows,
  animations
} from './assets/tokens/json'

export {
  useModal,
  useHelper,
  useToast,
  useDrawer,
  useTooltip,
  useTheme,
  useFieldErrors,
  useRandomNumber,
  useMcSvgIconProps
} from '@/composables'
export {
  McAvatar,
  McAccordion,
  McBadge,
  McCell,
  McChat,
  McChatComment,
  McChatForm,
  McChip,
  McBottomLoader,
  McButton,
  McCollapse,
  McDate,
  McContentFixed,
  McCropper,
  McDatepicker,
  McDraggable,
  McDrawer,
  McDrawerContainer,
  McDrawerContentTemplate,
  McDropdown,
  McDropdownPanel,
  McFieldCheckbox,
  McFieldGroup,
  McFieldRadioGroup,
  McFieldRadio,
  McFieldRange,
  McFieldSelect,
  McFieldText,
  McFieldToggle,
  McFilterChip,
  McFilter,
  McFilterPresets,
  McFilterTags,
  McFilterTypeDate,
  McFilterTypeRange,
  McFilterTypeRelation,
  McFilterTypeText,
  McGridCol,
  McGridRow,
  McIconShell,
  McMain,
  McModal,
  McModalContainer,
  McNoData,
  McInfinityLoadingTrigger,
  McNotification,
  McOverlay,
  McPreview,
  McProgress,
  McSeparator,
  McSideBar,
  McSideBarBottom,
  McSideBarButton,
  McSideBarCenter,
  McSideBarTop,
  McSlideUpDown,
  McSpinDigit,
  McSpinNumber,
  McStack,
  McSvgIcon,
  McTab,
  McTable,
  McTableCard,
  McTableCardHeader,
  McTabs,
  McTableSort,
  McTitle,
  McToast,
  McTopBar,
  McTableSkeletonLoading,
  McTooltip,
  McVirtualScroll,
  McWrapScroll
} from '@/components'

export default {
  install(app: App, options: IDSOptions = {}) {
    const defaultOptions: IDSOptions = {
      drawerComponents: {},
      modalComponents: {},
      toasts: {},
      defaultAvatar,
      colors: ThemesColors,
      themes: UiThemes,
      theme: Themes.Light,
      meta: {
        router: null
      }
    }

    const dsOptions = shallowReactive({
      ...defaultOptions,
      ...options,
      colors: options.colors ? createProxy(defaultOptions.colors!, options.colors) : defaultOptions.colors,
      themes: options.themes ? createProxy(defaultOptions.themes!, options.themes) : defaultOptions.themes,
      meta: options.meta ? createProxy(defaultOptions.meta!, options.meta) : defaultOptions.meta
    })

    app.config.globalProperties.$dsOptions = dsOptions
    app.provide('dsOptions', dsOptions)
    setStoredAppContext((app as App & { _context?: unknown })._context ?? null)
  }
}
